version: '3.4'

services:
  userservice.api:
    image: ${DOCKER_REGISTRY-}userserviceapi
    build:
      context: .
      dockerfile: UserService.Api/Dockerfile
  seq:
      image: datalust/seq:latest
      ports:
        - "5341:80"
      environment:
        - ACCEPT_EULA=Y
      restart: unless-stopped
      volumes:
        - ./seq-data:/data